[versions]
agp = "8.11.0"
hiltAndroid = "2.56.2"
hiltNavigationFragment = "1.2.0"
kotlin = "2.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0-alpha01" }
androidx-hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltNavigationFragment" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version = "2.7.2" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version = "2.7.2" }
core = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version = "12.1.2" }
glide = { module = "com.github.bumptech.glide:glide", version = "5.0.0-rc01" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.2.1" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0-alpha04" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.8.1" }

ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version = "3.1.3" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version = "3.1.3" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version = "3.1.3" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version = "3.1.3" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version = "3.1.3" }

material = { group = "com.google.android.material", name = "material", version = "1.14.0-alpha02" }
androidx-activity = { group = "androidx.activity", name = "activity", version = "1.12.0-alpha03" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
shimmer = { module = "com.facebook.shimmer:shimmer", version = "0.5.0" }
androidx-preference = { group = "androidx.preference", name = "preference", version = "1.2.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = {id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}